language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t akashiice/react-docker-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true akashiice/react-docker-test npm test -- --coverage

after_success:
    - docker build -t akashiice/multi-client ./client
    - docker build -t akashiice/multi-nginx ./nginx
    - docker build -t akashiice/multi-server ./server
    - docker build -t akashiice/multi-worker ./worker
    # Log into docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push them to docker hub
    - docker push akashiice/multi-client
    - docker push akashiice/multi-nginx
    - docker push akashiice/multi-server
    - docker push akashiice/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-docker"
    env: "MultiDocker-prod"
    bucket_name: "elasticbeanstalk-us-east-1-944093395421"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY