sudo: required
services:
    - docker

before_install:
    - docker build -t akashiice/react-docker-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true akashiice/react-docker-test npm test -- --coverage

after_success:
    - docker build -t akashiice/multi-client ./client
    - docker build -t akashiice/multi-nginx ./nginx
    - docker build -t akashiice/multi-server ./server
    - docker build -t akashiice/multi-worker ./worker
    # Log into docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    